### PR TITLE
Feat/hero section update

### PR DESCRIPTION
**Pull request by archx3**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [x] Feature
- [ ] Performance improvement
- [ ] Feature removal
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch or to a feature branch, _not_ the `main` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the
  issue number)
- [x] All tests are
  passing: https://github.com/massenergize/massenergize-campaigns/blob/main/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

**Other information:**

### CODE REVIEW

**Review by frimpongopoku — CHANGES_REQUESTED** [review]
Maybe you are not done yet, but this is what we see. 

Screenshot 2024-02-13 at 16 01 17

**Comment by archx3** [comment]
I see.
Ok

**Comment by archx3** [comment]
Fix it from your end @frimpongopoku.

**Comment by archx3** [comment]
I stepped away from my machine.
The bootstrap classes shouldn't be a problem.
You can write inline styles. 
They'll take precedence over the style applied by the classes.
It's not that complex.

**Comment by abdullai-t** [comment]
Screenshot 2024-02-13 at 5 08 20 PM

**Review by abdullai-t — APPROVED** [review]
LGTM

**Pull request merged**
